# Do not edit this file. Manage your settings on FreedomBox.

# A simple sieve script that applies to all users. Moves mail to Junk folder
# based on classification header set by rspamd.
# See: https://docs.gandi.net/en/gandimail/sieve/sieve_tutorial.html

require ["fileinto", "mailbox"];

if header :is "X-Spam" "Yes" {
  fileinto :create "Junk";
}
