#!/bin/sh

cat <<"EOF"

                         .--._    _.--.
                        (     \  /     )
                         \     /\     /
                          \_   \/   _/
                           /        \
                          (    /\    )
                           `--'  `--'

                           FreedomBox

FreedomBox is a pure blend of Debian GNU/Linux.  FreedomBox manual is
available in /usr/share/doc/plinth.
EOF
