#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

set -e

echo "Let's Encrypt calling deploy hook for FreedomBox:" \
     "Domains: '${RENEWED_DOMAINS}'" \
     "Lineage: '${RENEWED_LINEAGE}'"
/usr/bin/test -S /var/run/dbus/system_bus_socket && \
/usr/bin/gdbus call \
      --system \
      --dest org.freedombox.Service \
      --object-path /org/freedombox/Service/LetsEncrypt \
      --timeout 10 \
      --method org.freedombox.Service.LetsEncrypt.DeployHook \
      "${RENEWED_DOMAINS}" \
      "${RENEWED_LINEAGE}" \
      > /dev/null
