#!/bin/bash
#
# This file is part of FreedomBox.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

echo "Let's Encrypt calling deploy hook for FreedomBox:" \
     "Domains: '${RENEWED_DOMAINS}'" \
     "Lineage: '${RENEWED_LINEAGE}'"
/usr/bin/test -S /var/run/dbus/system_bus_socket && \
/usr/bin/gdbus call \
      --system \
      --dest org.freedombox.Service \
      --object-path /org/freedombox/Service/LetsEncrypt \
      --timeout 10 \
      --method org.freedombox.Service.LetsEncrypt.DeployHook \
      "${RENEWED_DOMAINS}" \
      "${RENEWED_LINEAGE}" \
      > /dev/null
