#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

set -e  # Exit with code on error

IFACE="$1"
ACTION="$2"

if [[ "$CONNECTION_ID" != *"BATMAN"* ]]; then
    exit 0
fi

case ${ACTION} in
    up)
        logger "Setting up B.A.T.M.A.N. Advanced on interface $IFACE"
        ip link set mtu 1560 dev ${IFACE}
        modprobe batman-adv
        echo "bat0" > /sys/class/net/${IFACE}/batman_adv/mesh_iface
        ip link set up dev bat0
        ;;
    down)
        logger "Clearing B.A.T.M.A.N. Advanced on interface $IFACE"
        ip link set down dev bat0
        echo "none" > /sys/class/net/${IFACE}/batman_adv/mesh_iface
        ip link set mtu 1500 dev ${IFACE}
        ;;
    *)
        ;;
esac
