<div id="spin-modal" class="modal fade" tabindex="-1" role="dialog"
     data-keyboard="false" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="text-align: center">
        <h3 class='title'></h3>
      </div>
      <div class="modal-body" >
        <div style="height:200px">
          <span id="spin-modal-center"
                style="position: absolute;display: block;top: 50%;left: 50%;">
          </span>
        </div>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>
