# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombox', '0001_initial'),
    ]

    replaces = [
        ('plinth', '0002_modulestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            options={'db_table': 'plinth_module'},
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('setup_version', models.IntegerField()),
            ],
        ),
    ]
