#!/bin/sh

set -e

case "$1" in
purge)
	deluser --system --quiet plinth || true
	rm -rf /var/lib/plinth

	# Remove legacy directory too
	rm -rf /var/log/plinth

  if [ -e '/etc/apt/sources.list.d/freedombox-backports.list' ]; then
      rm /etc/apt/sources.list.d/freedombox-backports.list
  fi
	;;
esac

#DEBHELPER#

exit 0
