#!/usr/bin/python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Configuration helper for Cockpit.
"""

import argparse

import augeas

from plinth import action_utils

CONFIG_FILE = '/etc/cockpit/cockpit.conf'


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')

    subparsers.add_parser('setup', help='Setup Cockpit configuration')

    subparsers.required = True
    return parser.parse_args()


def _load_augeas():
    """Initialize Augeas."""
    aug = augeas.Augeas(flags=augeas.Augeas.NO_LOAD +
                        augeas.Augeas.NO_MODL_AUTOLOAD)
    aug.set('/augeas/load/inifile/lens', 'Puppet.lns')
    aug.set('/augeas/load/inifile/incl[last() + 1]', CONFIG_FILE)
    aug.load()
    return aug


def subcommand_setup(arguments):
    """Setup Cockpit configuration."""
    aug = _load_augeas()
    aug.set('/files' + CONFIG_FILE + '/WebService/UrlRoot', '/_cockpit/')
    aug.remove('/files' + CONFIG_FILE + '/WebService/Origins')
    aug.save()
    action_utils.service_restart('cockpit.socket')
    # Accommodate changes in Apache configuration file from v1 to v2.
    action_utils.service_reload('apache2')


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
