#!/usr/bin/python3
# -*- mode: python -*-
#
# This file is part of FreedomBox.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
Configuration helper for FreedomBox general configuration.
"""

import argparse
import os

from plinth import action_utils
from plinth.modules.config import DEFAULT_APP_CONF_FILE_NAME


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')
    set_default_app = subparsers.add_parser(
        'set-default-app',
        help='Set the default app for this FreedomBox instance.')
    set_default_app.add_argument('app', help='name of the default app')

    subparsers.required = True
    return parser.parse_args()


def subcommand_set_default_app(arguments):
    """Set the default app for this FreedomBox."""
    conf_file_path = os.path.join('/etc/apache2/conf-available',
                                  DEFAULT_APP_CONF_FILE_NAME)

    redirect_rule = 'RedirectMatch "^/$" "/{}"\n'.format(arguments.app)

    with open(conf_file_path, 'w') as conf_file:
        conf_file.write(redirect_rule)

    action_utils.webserver_enable('default-app')


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
