#!/bin/bash
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

username="$1"
password="$2"

adduser --disabled-password --gecos "" "$username"
if [ $? -ne 0 ]; then
    echo "Failed to create user"
    exit 1
fi

adduser "$username" sudo
if [ $? -ne 0 ]; then
    echo "Failed to add user to sudo group"
    exit 2
fi

echo "$username:$password" | chpasswd
if [ $? -ne 0 ]; then
    echo "Failed to set user password"
    exit 3
fi
