#!/bin/sh
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Must be run as root.

username="$1"

ldapdelete -Y EXTERNAL -H ldapi:/// "uid=$username,ou=users,dc=thisbox"

if [ $? -eq 0 ]; then
    echo "Success: user deleted"
else
    echo "Failed: user delete failed"
    exit 1
fi

cat <<EOF |ldapmodify -Y EXTERNAL -H ldapi:///
dn: cn=admin,ou=groups,dc=thisbox
changetype: modify
delete: uniqueMember
uniqueMember: uid=$username,ou=users,dc=thisbox
EOF

if [ $? -eq 0 ]; then
    echo "Removed user from admin group"
elif [ $? -eq 16 ]; then
    echo "User was not in admin group"
elif [ $? -eq 65 ]; then
    echo "Cannot remove last LDAP admin user"
    exit 2
fi
