#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later

domainname="$1"
hostname=$(hostname)

if [ -z "$domainname" ] ; then
    if grep -q 127.0.1.1 /etc/hosts ; then
        sed -i "s/127.0.1.1.*/127.0.1.1       $hostname/" /etc/hosts
    else
        sed -i "/127.0.0.1.*/a \
            127.0.1.1        $hostname" /etc/hosts
    fi
else
    if grep -q 127.0.1.1 /etc/hosts ; then
        sed -i "s/127.0.1.1.*/127.0.1.1       $hostname.$domainname $hostname/" /etc/hosts
    else
        sed -i "/127.0.0.1.*/a \
            127.0.1.1       $hostname.$domainname $hostname" /etc/hosts
    fi
fi
