#!/bin/sh
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

domainname="$1"
hostname=$(hostname)

if [ -z "$domainname" ] ; then
    if grep -q 127.0.1.1 /etc/hosts ; then
        sed -i "s/127.0.1.1.*/127.0.1.1       $hostname/" /etc/hosts
    else
        sed -i "/127.0.0.1.*/a \
            127.0.1.1        $hostname" /etc/hosts
    fi
else
    if grep -q 127.0.1.1 /etc/hosts ; then
        sed -i "s/127.0.1.1.*/127.0.1.1       $hostname.$domainname $hostname/" /etc/hosts
    else
        sed -i "/127.0.0.1.*/a \
            127.0.1.1       $hostname.$domainname $hostname" /etc/hosts
    fi
fi
