#!/usr/bin/python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Actions for help module.
"""

import argparse
import subprocess


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')

    subparsers.add_parser('get-logs', help='Get latest FreedomBox logs')

    subparsers.required = True
    return parser.parse_args()


def subcommand_get_logs(_):
    """Get latest FreedomBox logs."""
    command = ['journalctl', '--no-pager', '--lines=100', '--unit=plinth']
    subprocess.run(command, check=True)


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
