#!/bin/sh
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

hostname="$1"

if [ -d /run/systemd/system ] ; then
    hostnamectl set-hostname --transient --static "$hostname"
else
    echo "$hostname" > /etc/hostname
    if [ -x /etc/init.d/hostname.sh ] ; then
	invoke-rc.d hostname.sh start
    else
	service hostname start
    fi
fi

service avahi-daemon restart
