#!/usr/bin/python3
# -*- mode: python -*-
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
Configuration helper for Mediawiki
"""

import argparse
import grp
import os
import grp
import pwd
import shutil
import subprocess

from plinth import action_utils
from plinth.utils import generate_password


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')

    subparsers.add_parser('enable', help='Enable mediawiki')
    subparsers.add_parser('disable', help='Disable mediawiki')
    subparsers.add_parser('setup', help='Setup mediawiki')

    subparsers.required = True
    return parser.parse_args()


def subcommand_setup(_):
    data_dir = '/var/lib/mediawiki-db/'
    if not os.path.exists(data_dir):
        os.mkdir(data_dir)
        subprocess.check_call([
            'php', '/usr/share/mediawiki/maintenance/install.php',
            '--confpath=/etc/mediawiki', '--dbtype=sqlite',
            '--dbpath=/var/lib/mediawiki-db/', '--scriptpath=/mediawiki',
            '--pass',
            generate_password(), 'Wiki', 'admin'
        ])
    uid = pwd.getpwnam("www-data").pw_uid
    gid = grp.getgrnam("www-data").gr_gid
    os.chown(data_dir, uid, gid)
    change_logo()


def change_logo():
    """Change the placeholder logo to mediawiki's official logo"""
    conf_file = '/var/lib/mediawiki/LocalSettings.php'
    with open(conf_file, 'r') as cf:
        data = cf.readlines()

    for linum, line in enumerate(data):
        if line.lstrip().startswith('$wgLogo'):
            data[linum] = line.replace('wiki', 'mediawiki')
            break

    with open(conf_file, 'w') as f:
        f.writelines(data)


def subcommand_enable(_):
    """Enable web configuration and reload."""
    action_utils.service_enable('mediawiki')
    action_utils.webserver_enable('mediawiki')


def subcommand_disable(_):
    """Disable web configuration and reload."""
    action_utils.webserver_disable('mediawiki')
    action_utils.service_disable('mediawiki')


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
