#!/bin/sh

# Usage: module-list-enabled python_root
# This will change when we switch to using aptitude.

# TODO: Replace this with something like 'aptitude search -F %p | grep "plinth-"'
if [ -e "$1"/modules/owncloud.py ] ; then
    echo "owncloud"
fi
