#!/usr/bin/python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Configuration helper for power controls.
"""

import argparse
import subprocess


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')

    subparsers.add_parser('restart', help='Restart the system')
    subparsers.add_parser('shutdown', help='Shut down the system')

    subparsers.required = True
    return parser.parse_args()


def subcommand_restart(_):
    """Restart the system."""
    subprocess.call('reboot')


def subcommand_shutdown(_):
    """Shut down the system."""
    subprocess.call(['shutdown', 'now'])


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
