#!/usr/bin/python3
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
Configuration helper for repro SIP proxy.
"""

import time
from urllib import request, error

import argparse
import augeas

from plinth import action_utils

CONFIG = '/etc/repro/repro.config'
AUG_PATH = '/files' + CONFIG + '/.anon/'


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')

    setup = subparsers.add_parser('setup', help='Configure repro')
    setup.add_argument('--domain', help='Domain name')

    add_domain = subparsers.add_parser('add-domain', help='Add domain name')
    add_domain.add_argument('--domain', help='Domain name')

    remove_domain = subparsers.add_parser('remove-domain',
                                          help='Remove domain name')
    remove_domain.add_argument('--domain', help='Domain name')

    return parser.parse_args()


def subcommand_setup(arguments):
    """Configure repro."""
    aug = load_augeas()

    # workaround for Debian bug #803113
    aug.set(AUG_PATH + 'Database1Path', '/var/lib/repro')
    aug.set(AUG_PATH + 'TLSPort', '5061')
    # let apache handle authentication
    aug.set(AUG_PATH + 'DisableHttpAuth', 'true')
    aug.save()

    action_utils.service_restart('repro')
    action_utils.webserver_enable('repro-plinth')

    if arguments.domain:
        while 1:
            tries = 0
            try:
                _add_domain(arguments.domain, restart=False)
                break
            except error.URLError:
                tries += 1
                if tries >= 30:
                    return
                time.sleep(2)

    action_utils.service_restart('repro')


def subcommand_add_domain(arguments):
    """Add domain name."""
    _add_domain(arguments.domain)


def _add_domain(domain, restart=True):
    """Add domain name."""
    request.urlopen(
        'http://localhost:5080/domains.html?domainUri=' + domain \
        + '&action=Add')

    if restart:
        action_utils.service_restart('repro')


def subcommand_remove_domain(arguments):
    """Remove domain name."""
    request.urlopen(
        'http://localhost:5080/domains.html?action=Remove&remove.' \
        + arguments.domain + '=on')

    action_utils.service_restart('repro')


def load_augeas():
    """Initialize Augeas."""
    aug = augeas.Augeas(flags=augeas.Augeas.NO_LOAD +
                        augeas.Augeas.NO_MODL_AUTOLOAD)
    aug.set('/augeas/load/Php/lens', 'Php.lns')
    aug.set('/augeas/load/Php/incl[last() + 1]', CONFIG)
    aug.load()
    return aug


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
