#!/usr/bin/python3
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
Configuration helper for repro SIP proxy.
"""

import argparse
import augeas

from plinth import action_utils

CONFIG = '/etc/repro/repro.config'
AUG_PATH = '/files' + CONFIG + '/.anon/'


def parse_arguments():
    """Return parsed command line arguments as dictionary."""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subcommand', help='Sub command')

    subparsers.add_parser('setup', help='Configure repro')

    return parser.parse_args()


def subcommand_setup(_):
    """Configure repro."""
    aug = load_augeas()

    # workaround for Debian bug #803113
    aug.set(AUG_PATH + 'Database1Path', '/var/lib/repro')
    aug.set(AUG_PATH + 'TLSPort', '5061')
    # let apache handle authentication
    aug.set(AUG_PATH + 'DisableHttpAuth', 'true')
    aug.save()

    action_utils.service_restart('repro')
    action_utils.webserver_enable('repro-plinth')



def load_augeas():
    """Initialize Augeas."""
    aug = augeas.Augeas(flags=augeas.Augeas.NO_LOAD +
                        augeas.Augeas.NO_MODL_AUTOLOAD)
    aug.set('/augeas/load/Php/lens', 'Php.lns')
    aug.set('/augeas/load/Php/incl[last() + 1]', CONFIG)
    aug.load()
    return aug


def main():
    """Parse arguments and perform all duties."""
    arguments = parse_arguments()

    subcommand = arguments.subcommand.replace('-', '_')
    subcommand_method = globals()['subcommand_' + subcommand]
    subcommand_method(arguments)


if __name__ == '__main__':
    main()
