#!/usr/bin/python3
# -*- mode: python -*-
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Helper to test whether action scripts use the correct PYTHONPATH.
"""

import plinth

print(plinth.__file__)
